springdoc:
  api-docs:
    enabled: true    
  swagger-ui.path: /swagger-ui.html

server:
  port: 8082

spring:
  data:
    mongodb:      
      uri: mongodb://localhost:27017/test
      repositories:
        type: reactive
  sleuth:
    reactor:
      enabled: true
  zipkin:
    enabled: false

  cloud:
    discovery:
      enabled: true

    